# Generated by Django 4.2.7 on 2023-12-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('comopsition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(max_length=2, verbose_name=(('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('CH', 'Chikan'), ('VG', 'vegetables')))),
                ('Product_image', models.ImageField(upload_to='Product')),
            ],
        ),
    ]
